In [1]:

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from datetime import date
from dateutil.relativedelta import relativedelta
import yfinance as yf
from datetime import datetime
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import LSTM, Dropout, Dense
from sklearn.model_selection import train_test_split

In [12]:
start_date = date.today() - relativedelta(years=5)
end_date = date.today()

start_datetime = datetime(start_date.year, start_date.month, start_date.day)
end_datetime = datetime(end_date.year, end_date.month, end_date.day)

# Download data
historic_data = yf.download('^NSEI', start=start_datetime, end=end_datetime)

historic_data.index = historic_data.index.strftime('%Y-%m-%d')

historic_data

# 👉 Convert to image (show first 10 rows for readability)
#fig, ax = plt.subplots(figsize=(12, 5))
#ax.axis('tight')
#ax.axis('off')
#
#table = ax.table(
#    cellText=historic_data.head(10).values,
#    colLabels=historic_data.columns,
#    rowLabels=historic_data.head(10).index,
#    loc='center'
#)

#plt.show()

/tmp/ipykernel_4204/3944458687.py:8: FutureWarning: YF.download() has changed argument auto_adjust default to True
  historic_data = yf.download('^NSEI', start=start_datetime, end=end_datetime)
[*********************100%***********************]  1 of 1 completed

Price              Close          High           Low          Open  Volume
Ticker             ^NSEI         ^NSEI         ^NSEI         ^NSEI   ^NSEI
Date
2021-04-15  14581.450195  14597.549805  14353.200195  14522.400391  568000
2021-04-16  14617.849609  14697.700195  14559.000000  14599.599609  577200
2021-04-19  14359.450195  14382.299805  14191.400391  14306.599609  512300
2021-04-20  14296.400391  14526.950195  14207.299805  14526.700195  467400
2021-04-22  14406.150391  14424.750000  14151.400391  14219.150391  524600
...                  ...           ...           ...           ...     ...
2026-04-07  23123.650391  23153.849609  22719.300781  22838.699219  477000
2026-04-08  23997.349609  24025.150391  23828.500000  23855.150391  639300
2026-04-09  23775.099609  23990.750000  23682.800781  23909.050781  466600
2026-04-10  24050.599609  24074.050781  23856.349609  23880.550781  481300
2026-04-13  23842.650391  23907.400391  23555.599609  23589.599609  488800

[1234 rows x 5 columns]

In [16]:

sentiment_data = pd.read_csv('/content/drive/MyDrive/data sets for  ml/csv_files for creat dataset/final_sentiments.csv', usecols=["Date Created", "Mode"])
sentiment_data.columns = ['Date','Sentiment']
sentiment_data.set_index('Date',inplace=True)

sentiment_data

            Sentiment
Date
2017-10-13         -1
2017-10-14          1
2017-10-15          1
2017-10-16         -1
2017-10-17          1
...               ...
2022-10-08         -1
2022-10-09          1
2022-10-10         -1
2022-10-11          1
2022-10-12         -1

[1825 rows x 1 columns]

In [17]:

historic_data.columns = historic_data.columns.get_level_values(0)

data = pd.merge(historic_data, sentiment_data, left_index=True, right_index=True)
data.dropna(inplace=True)

data

,Close,High,Low,Open,Volume,Sentiment
Date,,,,,,
2021-04-15,14581.450195,14597.549805,14353.200195,14522.400391,568000,-1
2021-04-16,14617.849609,14697.700195,14559.000000,14599.599609,577200,1
2021-04-19,14359.450195,14382.299805,14191.400391,14306.599609,512300,-1
2021-04-20,14296.400391,14526.950195,14207.299805,14526.700195,467400,-1
2021-04-22,14406.150391,14424.750000,14151.400391,14219.150391,524600,-1
...,...,...,...,...,...,...
2022-10-06,17331.800781,17428.800781,17315.650391,17379.250000,265500,1
2022-10-07,17314.650391,17337.349609,17216.949219,17287.199219,216300,1
2022-10-10,17241.000000,17280.150391,17064.699219,17094.349609,234000,-1
2022-10-11,16983.550781,17261.800781,16950.300781,17256.050781,282600,1
2022-10-12,17123.599609,17142.349609,16960.050781,17025.550781,256000,-1

In [18]:
data.to_csv('/content/drive/MyDrive/data sets for  ml/csv_files for creat dataset/training_dataset.csv')